[project]
name = "pico"
version = "0.1.0"
description = "the tiniest coding agent ever"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "strands-agents[all]>=1.19.0",
    "strands-agents-tools>=0.2.17",
]
